-- 0027_teacher_exam.sql
-- Run in the Supabase SQL Editor or via `supabase db push`.
--
-- The teacher test (src/teacher/teacherExam.ts, TeacherExam.tsx). Becoming a
-- teacher is no longer a self-declaration: a signed-in user passes a short
-- music-theory test and the SERVER inserts their `public.teachers` row. The
-- direct insert 0026 allowed (teachers_insert_own) is dropped, so the only
-- way in is `teacher_exam_answer` finishing a passed attempt.
--
-- Everything that decides the outcome lives here, never in the client:
--   - Questions are generated by rule on every attempt (random positions,
--     roots, keys, intervals, chord qualities), so there is nothing to
--     memorise and two attempts never repeat.
--   - The client gets ONE question at a time, without its answer, and the
--     server stamps when it was issued. An answer that arrives after the
--     question's limit (+ ANSWER_GRACE_MS for the round trip) counts wrong
--     whatever was picked — the countdown on screen is only a display.
--   - The limits (8–12 s) are long enough for someone who knows the theory
--     and too short to type the question into a chatbot and read the reply.
--     The two picture questions (a marked place on the neck, a note on the
--     staff) have no text to copy at all.
--   - Starting a new attempt closes any unfinished one as failed, so leaving
--     mid-test can't be used to skip hard questions.
--
-- Shape: 12 questions, 2 of each kind, in a shuffled order. Pass mark 10/12.
-- After a failed attempt the next one opens 24 hours later; after the second
-- failure and every later one, 7 days later. Admins may always (re)take it —
-- a practice run that never changes their own row.
--
-- Spelled notes travel as {"l": letter 0..6 (C D E F G A B), "a": -1|0|1};
-- the client renders them in the player's notation (A-B-C or Do-Re-Mi).
-- Only single sharps/flats are ever generated (a root that would need a
-- double accidental is re-drawn), so every name on screen is an ordinary one.
--
-- teacher_exam_attempts has RLS on and no client policies except an admin
-- read — the stored questions include their answers, so only the
-- SECURITY DEFINER functions below touch it.
--
-- The app has not launched, so teachers rows created by the old
-- self-declaration (test accounts) are left as they are.

-- ── Close the self-declaration path from 0026 ───────────────────────────
drop policy if exists teachers_insert_own on public.teachers;
revoke insert on public.teachers from authenticated;

-- 0026's Premium sync helpers were left executable by every role (Postgres
-- grants EXECUTE to PUBLIC by default). They only ever compute the correct
-- state, but nobody outside the database should be able to fire a sweep.
revoke all on function public.sync_teacher_premium(uuid) from public, anon, authenticated;
revoke all on function public.sync_all_teacher_premium() from public, anon, authenticated;
revoke all on function public.class_qualifies_for_premium(uuid) from public, anon, authenticated;

-- ── Attempts ────────────────────────────────────────────────────────────
create table if not exists public.teacher_exam_attempts (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users (id) on delete cascade,
  instrument_id text not null check (instrument_id in ('guitar', 'bass', 'ukulele')),
  display_name  text check (display_name is null or char_length(display_name) <= 60),
  -- [{kind, limit_ms, prompt, options, answer}] — answer is never sent out.
  questions     jsonb not null,
  -- [{choice, correct, ms}] in question order.
  answers       jsonb not null default '[]'::jsonb,
  current_index integer not null default 0,
  issued_at     timestamptz,
  started_at    timestamptz not null default now(),
  finished_at   timestamptz,
  score         integer,
  passed        boolean
);

create index if not exists teacher_exam_attempts_user_idx
  on public.teacher_exam_attempts (user_id, started_at desc);

alter table public.teacher_exam_attempts enable row level security;

drop policy if exists teacher_exam_attempts_admin_read on public.teacher_exam_attempts;
create policy teacher_exam_attempts_admin_read on public.teacher_exam_attempts
  for select to authenticated
  using (public.is_admin());

revoke all on public.teacher_exam_attempts from anon, authenticated;
grant select on public.teacher_exam_attempts to authenticated;

-- ── Note spelling helpers ───────────────────────────────────────────────
create or replace function public.teacher_exam_note(l integer, a integer)
returns jsonb language sql immutable set search_path = public as $$
  select jsonb_build_object('l', l, 'a', a);
$$;

create or replace function public.teacher_exam_pc(n jsonb)
returns integer language sql immutable set search_path = public as $$
  select ((((array[0, 2, 4, 5, 7, 9, 11])[(n->>'l')::int + 1] + (n->>'a')::int) % 12) + 12) % 12;
$$;

-- The note `steps` letters and `semis` semitones above `root`, spelled by
-- letter; null when that spelling would need a double sharp / flat.
create or replace function public.teacher_exam_up(root jsonb, steps integer, semis integer)
returns jsonb language plpgsql immutable set search_path = public as $$
declare
  l integer := ((root->>'l')::int + steps) % 7;
  target integer := (public.teacher_exam_pc(root) + semis) % 12;
  d integer;
begin
  d := (((target - (array[0, 2, 4, 5, 7, 9, 11])[l + 1]) % 12) + 12) % 12;
  if d > 6 then d := d - 12; end if;
  if abs(d) > 1 then return null; end if;
  return public.teacher_exam_note(l, d);
end;
$$;

create or replace function public.teacher_exam_rand(n integer)
returns integer language sql volatile set search_path = public as $$
  select floor(random() * n)::int;
$$;

create or replace function public.teacher_exam_shuffle(items jsonb[])
returns jsonb[] language sql volatile set search_path = public as $$
  select coalesce(array_agg(x order by random()), array[]::jsonb[]) from unnest(items) x;
$$;

-- One finished question: the correct option plus the first three distinct
-- usable distractors from `candidates` (priority order; nulls skipped),
-- shuffled, with the correct option's index recorded as `answer`.
create or replace function public.teacher_exam_pack(
  kind text, limit_ms integer, prompt jsonb, correct jsonb, candidates jsonb[]
)
returns jsonb language plpgsql volatile set search_path = public as $$
declare
  picked jsonb[] := array[]::jsonb[];
  c jsonb;
  opts jsonb;
  ans integer;
begin
  foreach c in array candidates loop
    exit when coalesce(array_length(picked, 1), 0) = 3;
    if c is not null and c <> correct and not (c = any (picked)) then
      picked := array_append(picked, c);
    end if;
  end loop;
  if coalesce(array_length(picked, 1), 0) < 3 then
    raise exception 'teacher exam: too few distractors for %', kind;
  end if;
  select jsonb_agg(o order by r) into opts
    from (select o, random() as r from unnest(array_append(picked, correct)) o) x;
  select (i - 1)::int into ans
    from jsonb_array_elements(opts) with ordinality e(o, i) where e.o = correct;
  return jsonb_build_object('kind', kind, 'limit_ms', limit_ms, 'prompt', prompt,
    'options', opts, 'answer', ans);
end;
$$;

-- Roots used for intervals and chords: the naturals plus the common
-- black-key names.
create or replace function public.teacher_exam_roots()
returns jsonb[] language sql immutable set search_path = public as $$
  select array[
    public.teacher_exam_note(0, 0), public.teacher_exam_note(1, 0), public.teacher_exam_note(2, 0),
    public.teacher_exam_note(3, 0), public.teacher_exam_note(4, 0), public.teacher_exam_note(5, 0),
    public.teacher_exam_note(6, 0), public.teacher_exam_note(6, -1), public.teacher_exam_note(2, -1),
    public.teacher_exam_note(5, -1), public.teacher_exam_note(1, -1), public.teacher_exam_note(3, 1),
    public.teacher_exam_note(0, 1)
  ];
$$;

-- Major keys: tonic + signed signature (+n sharps, −n flats).
create or replace function public.teacher_exam_keys()
returns table (tonic jsonb, n integer) language sql immutable set search_path = public as $$
  values
    (public.teacher_exam_note(0, 0), 0),  (public.teacher_exam_note(4, 0), 1),
    (public.teacher_exam_note(1, 0), 2),  (public.teacher_exam_note(5, 0), 3),
    (public.teacher_exam_note(2, 0), 4),  (public.teacher_exam_note(6, 0), 5),
    (public.teacher_exam_note(3, 1), 6),  (public.teacher_exam_note(3, 0), -1),
    (public.teacher_exam_note(6, -1), -2), (public.teacher_exam_note(2, -1), -3),
    (public.teacher_exam_note(5, -1), -4), (public.teacher_exam_note(1, -1), -5),
    (public.teacher_exam_note(4, -1), -6);
$$;

-- Chord tones above the root (letters, semitones) per quality.
create or replace function public.teacher_exam_chord(root jsonb, q text)
returns jsonb language plpgsql immutable set search_path = public as $$
declare
  steps integer[];
  semis integer[];
  res jsonb := jsonb_build_array(root);
  n jsonb;
begin
  case q
    when 'maj'  then steps := array[2, 4];    semis := array[4, 7];
    when 'min'  then steps := array[2, 4];    semis := array[3, 7];
    when 'dim'  then steps := array[2, 4];    semis := array[3, 6];
    when 'aug'  then steps := array[2, 4];    semis := array[4, 8];
    when 'dom7' then steps := array[2, 4, 6]; semis := array[4, 7, 10];
    when 'maj7' then steps := array[2, 4, 6]; semis := array[4, 7, 11];
    when 'min7' then steps := array[2, 4, 6]; semis := array[3, 7, 10];
    when 'm7b5' then steps := array[2, 4, 6]; semis := array[3, 6, 10];
    else raise exception 'teacher exam: unknown chord quality %', q;
  end case;
  for i in 1 .. array_length(steps, 1) loop
    n := public.teacher_exam_up(root, steps[i], semis[i]);
    if n is null then return null; end if;
    res := res || jsonb_build_array(n);
  end loop;
  return res;
end;
$$;

-- ── Question generators ─────────────────────────────────────────────────

-- A marked place on the neck (frets 1–12): name the note. Options are pitch
-- classes, shown with the player's own sharps/flats preference.
create or replace function public.teacher_exam_q_neck(instrument text)
returns jsonb language plpgsql volatile set search_path = public as $$
declare
  -- Open-string pitch classes, string 1 (highest) first — standard tunings,
  -- matching getInstrument(id) in src/utils/instruments.ts.
  opens integer[] := case instrument
    when 'bass' then array[7, 2, 9, 4]
    when 'ukulele' then array[9, 4, 0, 7]
    else array[4, 11, 7, 2, 9, 4] end;
  s integer := 1 + public.teacher_exam_rand(array_length(opens, 1));
  f integer := 1 + public.teacher_exam_rand(12);
  pc integer := (opens[s] + f) % 12;
begin
  return public.teacher_exam_pack('neck', 8000,
    jsonb_build_object('string', s, 'fret', f),
    jsonb_build_object('pc', pc),
    public.teacher_exam_shuffle(array[
      jsonb_build_object('pc', (pc + 1) % 12), jsonb_build_object('pc', (pc + 11) % 12),
      jsonb_build_object('pc', (pc + 2) % 12), jsonb_build_object('pc', (pc + 10) % 12)
    ]));
end;
$$;

-- A note on the staff (treble for guitar/ukulele, bass clef for bass), up
-- to two ledger lines either side: name it. `pos` counts lines-and-spaces
-- from the bottom line (src/utils/staff.ts).
create or replace function public.teacher_exam_q_staff(instrument text)
returns jsonb language plpgsql volatile set search_path = public as $$
declare
  clef text := case when instrument = 'bass' then 'bass' else 'treble' end;
  -- Bottom line: E (letter 2) in treble, G (letter 4) in bass.
  bottom integer := case when clef = 'bass' then 4 else 2 end;
  pos integer := -4 + public.teacher_exam_rand(17);
  l integer := (((bottom + pos) % 7) + 7) % 7;
  r integer := public.teacher_exam_rand(10);
  a integer := case when r < 6 then 0 when r < 8 then 1 else -1 end;
  correct jsonb;
  fix_a integer;
begin
  -- No E♯ / B♯ / F♭ / C♭ — fair game in theory, not what this test is about.
  if (a = 1 and l in (2, 6)) or (a = -1 and l in (0, 3)) then a := 0; end if;
  correct := public.teacher_exam_note(l, a);
  fix_a := case when a = 0 then (case when l in (2, 6) then -1 else 1 end) else 0 end;
  return public.teacher_exam_pack('staff', 8000,
    jsonb_build_object('clef', clef, 'pos', pos,
      'sign', case a when 1 then '#' when -1 then 'b' else '' end),
    correct,
    public.teacher_exam_shuffle(array[
      -- the neighbouring line/space, and the other clef's reading
      public.teacher_exam_note((l + 1) % 7, case when (a = 1 and (l + 1) % 7 in (2, 6)) or (a = -1 and (l + 1) % 7 in (0, 3)) then 0 else a end),
      public.teacher_exam_note((l + 6) % 7, case when (a = 1 and (l + 6) % 7 in (2, 6)) or (a = -1 and (l + 6) % 7 in (0, 3)) then 0 else a end),
      public.teacher_exam_note((l + 2) % 7, case when (a = 1 and (l + 2) % 7 in (2, 6)) or (a = -1 and (l + 2) % 7 in (0, 3)) then 0 else a end)
    ]) || array[public.teacher_exam_note(l, fix_a)]);
end;
$$;

-- From a root up to a spelled note: which interval? The distractors are the
-- enharmonic twin (A5 vs m6), the other qualities of the same number, then
-- the sizes a semitone away.
create or replace function public.teacher_exam_q_interval()
returns jsonb language plpgsql volatile set search_path = public as $$
declare
  codes text[]    := array['m2', 'M2', 'm3', 'M3', 'P4', 'A4', 'd5', 'P5', 'A5', 'm6', 'M6', 'm7', 'M7'];
  steps integer[] := array[1, 1, 2, 2, 3, 3, 4, 4, 4, 5, 5, 6, 6];
  semis integer[] := array[1, 2, 3, 4, 5, 6, 6, 7, 8, 8, 9, 10, 11];
  roots jsonb[] := public.teacher_exam_roots();
  root jsonb;
  target jsonb;
  i integer;
  cands jsonb[];
begin
  loop
    root := roots[1 + public.teacher_exam_rand(array_length(roots, 1))];
    i := 1 + public.teacher_exam_rand(13);
    target := public.teacher_exam_up(root, steps[i], semis[i]);
    exit when target is not null;
  end loop;
  select array_agg(jsonb_build_object('iv', codes[j]) order by
      case when semis[j] = semis[i] then 0
           when steps[j] = steps[i] then 1
           when abs(semis[j] - semis[i]) = 1 then 2
           else 3 end,
      random())
    into cands
    from generate_subscripts(codes, 1) j
    where j <> i;
  return public.teacher_exam_pack('interval', 10000,
    jsonb_build_object('from', root, 'to', target),
    jsonb_build_object('iv', codes[i]), cands);
end;
$$;

-- Key signatures: how many sharps/flats in a key, which key has a given
-- signature, or a key's relative minor.
create or replace function public.teacher_exam_q_key()
returns jsonb language plpgsql volatile set search_path = public as $$
declare
  k record;
  v integer := public.teacher_exam_rand(3);
  cands jsonb[];
begin
  if v = 0 then
    select * into k from public.teacher_exam_keys() order by random() limit 1;
    select array_agg(jsonb_build_object('n', c) order by pri, random()) into cands
      from (values (-k.n, 0), (k.n + 1, 1), (k.n - 1, 1), (k.n + 2, 2), (k.n - 2, 2)) d(c, pri)
      where abs(c) <= 7;
    return public.teacher_exam_pack('key', 8000,
      jsonb_build_object('v', 'count', 'key', k.tonic), jsonb_build_object('n', k.n), cands);
  elsif v = 1 then
    select * into k from public.teacher_exam_keys() where n <> 0 order by random() limit 1;
    select array_agg(x.tonic order by case when x.n = -k.n then 0 else abs(x.n - k.n) end, random())
      into cands
      from public.teacher_exam_keys() x
      where x.n <> k.n and (x.n = -k.n or abs(x.n - k.n) <= 2);
    return public.teacher_exam_pack('key', 8000,
      jsonb_build_object('v', 'which', 'n', k.n), k.tonic, cands);
  else
    select * into k from public.teacher_exam_keys() order by random() limit 1;
    return public.teacher_exam_pack('key', 8000,
      jsonb_build_object('v', 'relative', 'key', k.tonic),
      jsonb_build_object('root', public.teacher_exam_up(k.tonic, 5, 9), 'q', 'min'),
      array[
        -- a minor third UP instead of down — the classic slip — then ii, iii, v
        case when public.teacher_exam_up(k.tonic, 2, 3) is null then null
             else jsonb_build_object('root', public.teacher_exam_up(k.tonic, 2, 3), 'q', 'min') end,
        jsonb_build_object('root', public.teacher_exam_up(k.tonic, 2, 4), 'q', 'min'),
        jsonb_build_object('root', public.teacher_exam_up(k.tonic, 1, 2), 'q', 'min'),
        jsonb_build_object('root', public.teacher_exam_up(k.tonic, 4, 7), 'q', 'min')
      ]);
  end if;
end;
$$;

-- Chords: name a chord from its notes, or pick a chord's notes. All four
-- options share the root and the size (triad / seventh), so only knowing
-- the quality tells them apart.
create or replace function public.teacher_exam_q_chord()
returns jsonb language plpgsql volatile set search_path = public as $$
declare
  roots jsonb[] := public.teacher_exam_roots();
  qs text[];
  root jsonb;
  q text;
  ok boolean;
  x text;
  cands jsonb[];
begin
  loop
    qs := case when public.teacher_exam_rand(2) = 0
      then array['maj', 'min', 'dim', 'aug'] else array['dom7', 'maj7', 'min7', 'm7b5'] end;
    root := roots[1 + public.teacher_exam_rand(array_length(roots, 1))];
    ok := true;
    foreach x in array qs loop
      if public.teacher_exam_chord(root, x) is null then ok := false; end if;
    end loop;
    exit when ok;
  end loop;
  q := qs[1 + public.teacher_exam_rand(4)];
  if public.teacher_exam_rand(2) = 0 then
    select array_agg(jsonb_build_object('root', root, 'q', y) order by random()) into cands
      from unnest(qs) y where y <> q;
    return public.teacher_exam_pack('chord', 12000,
      jsonb_build_object('v', 'name', 'notes', public.teacher_exam_chord(root, q)),
      jsonb_build_object('root', root, 'q', q), cands);
  else
    select array_agg(jsonb_build_object('notes', public.teacher_exam_chord(root, y)) order by random())
      into cands from unnest(qs) y where y <> q;
    return public.teacher_exam_pack('chord', 12000,
      jsonb_build_object('v', 'notes', 'chord', jsonb_build_object('root', root, 'q', q)),
      jsonb_build_object('notes', public.teacher_exam_chord(root, q)), cands);
  end if;
end;
$$;

-- Harmony in a major key (up to five sharps/flats): the chord on a degree,
-- or the note of a degree.
create or replace function public.teacher_exam_q_diatonic()
returns jsonb language plpgsql volatile set search_path = public as $$
declare
  semis integer[] := array[0, 2, 4, 5, 7, 9, 11];
  quals text[] := array['maj', 'min', 'min', 'maj', 'maj', 'min', 'dim'];
  k record;
  d integer := 2 + public.teacher_exam_rand(6);
  prev integer := d - 1;
  nxt integer := d % 7 + 1;
  note_d jsonb;
  swapped text;
begin
  select * into k from public.teacher_exam_keys() where abs(n) <= 5 order by random() limit 1;
  note_d := public.teacher_exam_up(k.tonic, d - 1, semis[d]);
  if public.teacher_exam_rand(2) = 0 then
    swapped := case quals[d] when 'maj' then 'min' when 'min' then 'maj' else 'min' end;
    return public.teacher_exam_pack('diatonic', 12000,
      jsonb_build_object('v', 'chord', 'key', k.tonic, 'deg', d),
      jsonb_build_object('root', note_d, 'q', quals[d]),
      array[jsonb_build_object('root', note_d, 'q', swapped)] || public.teacher_exam_shuffle(array[
        jsonb_build_object('root', public.teacher_exam_up(k.tonic, prev - 1, semis[prev]), 'q', quals[prev]),
        jsonb_build_object('root', public.teacher_exam_up(k.tonic, nxt - 1, semis[nxt]), 'q', quals[nxt]),
        jsonb_build_object('root', note_d, 'q', case when quals[d] = 'dim' then 'min' else 'dim' end)
      ]));
  else
    return public.teacher_exam_pack('diatonic', 10000,
      jsonb_build_object('v', 'degree', 'key', k.tonic, 'deg', d),
      note_d,
      array[
        -- the right letter with the wrong sharp/flat, then the neighbours
        case when abs((note_d->>'a')::int + 1) <= 1
             then public.teacher_exam_note((note_d->>'l')::int, (note_d->>'a')::int + 1) end,
        case when abs((note_d->>'a')::int - 1) <= 1
             then public.teacher_exam_note((note_d->>'l')::int, (note_d->>'a')::int - 1) end,
        public.teacher_exam_up(k.tonic, prev - 1, semis[prev]),
        public.teacher_exam_up(k.tonic, nxt - 1, semis[nxt])
      ]);
  end if;
end;
$$;

-- The 12 questions of one attempt: two of each kind, shuffled, never the
-- same prompt twice.
create or replace function public.teacher_exam_build(instrument text)
returns jsonb language plpgsql volatile set search_path = public as $$
declare
  kinds text[];
  kind text;
  q jsonb;
  res jsonb := '[]'::jsonb;
  prompts jsonb[] := array[]::jsonb[];
begin
  select array_agg(x order by random()) into kinds
    from unnest(array['neck', 'neck', 'staff', 'staff', 'interval', 'interval',
                      'key', 'key', 'chord', 'chord', 'diatonic', 'diatonic']) x;
  foreach kind in array kinds loop
    loop
      q := case kind
        when 'neck' then public.teacher_exam_q_neck(instrument)
        when 'staff' then public.teacher_exam_q_staff(instrument)
        when 'interval' then public.teacher_exam_q_interval()
        when 'key' then public.teacher_exam_q_key()
        when 'chord' then public.teacher_exam_q_chord()
        else public.teacher_exam_q_diatonic() end;
      exit when not (q->'prompt' = any (prompts));
    end loop;
    prompts := array_append(prompts, q->'prompt');
    res := res || jsonb_build_array(q);
  end loop;
  return res;
end;
$$;

-- When the next attempt opens for this user: null = now.
create or replace function public.teacher_exam_retry_at(uid uuid)
returns timestamptz language sql stable set search_path = public as $$
  select case
    when count(*) = 0 then null
    when count(*) = 1 then max(finished_at) + interval '24 hours'
    else max(finished_at) + interval '7 days'
  end
  from public.teacher_exam_attempts
  where user_id = uid and passed = false;
$$;

-- ── Client RPCs ─────────────────────────────────────────────────────────

-- What the intro screen needs: am I a teacher, and when may I (re)take it.
create or replace function public.teacher_exam_status()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  retry timestamptz;
begin
  if uid is null then raise exception 'not signed in'; end if;
  retry := public.teacher_exam_retry_at(uid);
  return jsonb_build_object(
    'is_teacher', exists (select 1 from public.teachers where user_id = uid),
    'is_admin', public.is_admin(),
    'retry_at', case when retry > now() and not public.is_admin() then retry end,
    'failed_attempts', (select count(*) from public.teacher_exam_attempts where user_id = uid and passed = false),
    'questions', 12,
    'pass_mark', 10
  );
end;
$$;

create or replace function public.teacher_exam_start(p_instrument text, p_display_name text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  admin boolean := public.is_admin();
  retry timestamptz;
  qs jsonb;
  attempt_id uuid;
begin
  if uid is null then raise exception 'not signed in'; end if;
  if p_instrument not in ('guitar', 'bass', 'ukulele') then raise exception 'bad instrument'; end if;
  if not admin and exists (select 1 from public.teachers where user_id = uid) then
    return jsonb_build_object('status', 'already');
  end if;

  -- An attempt left open (app closed, page reloaded) ends here as a failure.
  update public.teacher_exam_attempts a
     set finished_at = now(),
         passed = false,
         score = (select count(*) from jsonb_array_elements(a.answers) e where (e->>'correct')::boolean)
   where a.user_id = uid and a.finished_at is null;

  retry := public.teacher_exam_retry_at(uid);
  if not admin and retry > now() then
    return jsonb_build_object('status', 'cooldown', 'retry_at', retry);
  end if;

  qs := public.teacher_exam_build(p_instrument);
  insert into public.teacher_exam_attempts (user_id, instrument_id, display_name, questions, issued_at)
  values (uid, p_instrument, left(btrim(coalesce(p_display_name, '')), 60), qs, clock_timestamp())
  returning id into attempt_id;

  return jsonb_build_object('status', 'question', 'attempt_id', attempt_id,
    'index', 0, 'total', jsonb_array_length(qs), 'question', (qs->0) - 'answer');
end;
$$;

-- Answer the current question (p_choice = option index, or -1 when the time
-- ran out). Returns the next question, or the result after the last one.
create or replace function public.teacher_exam_answer(p_attempt uuid, p_choice integer)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  ANSWER_GRACE_MS constant integer := 2500;
  PASS_MARK constant integer := 10;
  uid uuid := auth.uid();
  att public.teacher_exam_attempts%rowtype;
  q jsonb;
  total integer;
  elapsed_ms integer;
  ok boolean;
  v_answers jsonb;
  v_score integer;
  v_passed boolean;
  by_kind jsonb;
begin
  if uid is null then raise exception 'not signed in'; end if;
  select * into att from public.teacher_exam_attempts
   where id = p_attempt and user_id = uid and finished_at is null
   for update;
  if not found then raise exception 'no open exam'; end if;

  total := jsonb_array_length(att.questions);
  q := att.questions->att.current_index;
  elapsed_ms := floor(extract(epoch from (clock_timestamp() - att.issued_at)) * 1000)::int;
  ok := elapsed_ms <= (q->>'limit_ms')::int + ANSWER_GRACE_MS
        and p_choice = (q->>'answer')::int;
  v_answers := att.answers || jsonb_build_array(
    jsonb_build_object('choice', p_choice, 'correct', ok, 'ms', elapsed_ms));

  if att.current_index + 1 < total then
    update public.teacher_exam_attempts
       set answers = v_answers, current_index = att.current_index + 1, issued_at = clock_timestamp()
     where id = att.id;
    return jsonb_build_object('status', 'question', 'correct', ok, 'attempt_id', att.id,
      'index', att.current_index + 1, 'total', total,
      'question', (att.questions->(att.current_index + 1)) - 'answer');
  end if;

  select count(*) filter (where (a->>'correct')::boolean) into v_score
    from jsonb_array_elements(v_answers) a;
  v_passed := v_score >= PASS_MARK;
  update public.teacher_exam_attempts
     set answers = v_answers, finished_at = now(), score = v_score, passed = v_passed
   where id = att.id;

  select jsonb_object_agg(kind, n) into by_kind from (
    select qq->>'kind' as kind, count(*) filter (where (aa->>'correct')::boolean) as n
      from jsonb_array_elements(att.questions) with ordinality qx(qq, i)
      join jsonb_array_elements(v_answers) with ordinality ax(aa, j) on i = j
     group by qq->>'kind'
  ) s;

  if v_passed then
    insert into public.teachers (user_id, display_name)
    values (uid, nullif(att.display_name, ''))
    on conflict (user_id) do nothing;
  end if;

  return jsonb_build_object('status', 'finished', 'correct', ok, 'score', v_score, 'total', total,
    'pass_mark', PASS_MARK, 'passed', v_passed, 'by_kind', by_kind,
    'retry_at', case when v_passed then null else public.teacher_exam_retry_at(uid) end);
end;
$$;

-- Only the three RPCs are callable; the generators and helpers stay internal.
do $$
declare f record;
begin
  for f in
    select p.oid::regprocedure as sig from pg_proc p
     where p.pronamespace = 'public'::regnamespace and p.proname like 'teacher\_exam\_%'
  loop
    execute format('revoke all on function %s from public, anon, authenticated', f.sig);
  end loop;
end $$;

grant execute on function public.teacher_exam_status() to authenticated;
grant execute on function public.teacher_exam_start(text, text) to authenticated;
grant execute on function public.teacher_exam_answer(uuid, integer) to authenticated;
